[build]
  publish = "."
  functions = "functions"

[functions]
  # Força o uso de uma versão estável para todas as funções
  python_version = "3.10"

[functions."process_pdf"]
  runtime = "python3.10"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
