[build]
  publish = "."
  functions = "functions"

# Configuramos o runtime especificamente para funções Python
[functions."process_pdf"]
  runtime = "python3.8"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
