[build]
  publish = "." # Onde est√° seu index.html
  functions = "functions"

[functions]
  # Removemos o node_bundle que causou o erro
  # E garantimos o runtime correto para o Python
  runtime = "python3.8"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200